export default class Model {
    constructor() {
        this.data = {
            movies: [
                { 
                    movieID: 0,
                    title: 'A Beautiful Mind',
                    genre: 'Drama; Biography',
                    movieBy: 'Ron Howard',
                    movieDate: 2001,
                    rating: 8.2,
                    status: "Finished",
                },
                { 
                    movieID: 1,
                    title: 'The Lord of the Rings: The Return of the King',
                    genre: 'Drama; Action; Adventure',
                    movieBy: 'Peter Jackson',
                    movieDate: 2003,
                    rating: 8.9,
                    status: "Finished",
                },
                { 
                    movieID: 2,
                    title: 'North by Northwest',
                    genre: 'Adventure; Action; Mystery',
                    movieBy: 'Alfred Hitchcock',
                    movieDate: 1959,
                    rating: 8.3,
                    status: "Finished",
                },
                { 
                    movieID: 3,
                    title: 'Paths of Glory',
                    genre: 'Drama; War',
                    movieBy: 'Stanley Kubrick',
                    movieDate: 1957,
                    rating: 8.4,
                    status: "Finished",
                },
                { 
                    movieID: 4,
                    title: 'Heat',
                    genre: 'Drama; Crime; Action',
                    movieBy: 'Michael Mann',
                    movieDate: 1995,
                    rating: 8.2,
                    status: "Finished",
                },
                { 
                    movieID: 5,
                    title: '12 Years a Slave',
                    genre: 'Drama; History; Biography',
                    movieBy: 'Steve McQueen',
                    movieDate: 2013,
                    rating: 8.1,
                    status: "Finished",
                },
                { 
                    movieID: 6,
                    title: 'Room',
                    genre: 'Drama; Thriller',
                    movieBy: 'Lenny Abrahamson',
                    movieDate: 2015,
                    rating: 8.1,
                    status: "Finished",
                },
                { 
                    movieID: 7,
                    title: 'Before Sunrise',
                    genre: 'Drama; Romance',
                    movieBy: 'Richard Linklater',
                    movieDate: 1995,
                    rating: 8.1,
                    status: "Finished",
                },
                { 
                    movieID: 8,
                    title: 'The Good, the Bad and the Ugly',
                    genre: 'Adventure; Western',
                    movieBy: 'Sergio Leone',
                    movieDate: 1966,
                    rating: 8.8,
                    status: "Finished",
                },
                { 
                    movieID: 9,
                    title: 'The Apartment',
                    genre: 'Drama; Romance; Comedy',
                    movieBy: 'Billy Wilder',
                    movieDate: 1960,
                    rating: 8.2,
                    status: "Finished",
                }
            ],
        };
    }
}
