export default class Model {
    constructor() {
        this.data = {
            movies: [
                { 
                    movieID: 0,
                    title: 'A Beautiful Mind',
                    genre: 'Drama Biography',
                    director: 'Ron Howard',
                    movieDate: 2001,
                    rating: '-',
                    status: "Not Watched",
                },
                { 
                    movieID: 1,
                    title: 'The Lord of the Rings: The Return of the King',
                    genre: 'Drama Action Adventure',
                    director: 'Peter Jackson',
                    movieDate: 2003,
                    rating: '-',
                    status: "Not Watched",
                },
                { 
                    movieID: 2,
                    title: 'North by Northwest',
                    genre: 'Adventure Action',
                    director: 'Alfred Hitchcock',
                    movieDate: 1959,
                    rating: 8.3,
                    status: "Finished",
                },
                { 
                    movieID: 3,
                    title: 'Paths of Glory',
                    genre: 'Drama',
                    director: 'Stanley Kubrick',
                    movieDate: 1957,
                    rating: 7.2,
                    status: "Started",
                },
                { 
                    movieID: 4,
                    title: 'Heat',
                    genre: 'Drama Crime Action',
                    director: 'Michael Mann',
                    movieDate: 1995,
                    rating: 8.2,
                    status: "Finished",
                },
                { 
                    movieID: 5,
                    title: '12 Years a Slave',
                    genre: 'Drama History Biography',
                    director: 'Steve McQueen',
                    movieDate: 2013,
                    rating: 10,
                    status: "Started",
                },
                { 
                    movieID: 6,
                    title: 'Room',
                    genre: 'Drama Thriller',
                    director: 'Lenny Abrahamson',
                    movieDate: 2015,
                    rating: 8.2,
                    status: "Started",
                },
                { 
                    movieID: 7,
                    title: 'Before Sunrise',
                    genre: 'Drama Romance',
                    director: 'Richard Linklater',
                    movieDate: 1995,
                    rating: '-',
                    status: "Not Watched",
                },
                { 
                    movieID: 8,
                    title: 'The Good, the Bad and the Ugly',
                    genre: 'Adventure Western',
                    director: 'Sergio Leone',
                    movieDate: 1966,
                    rating: 8.8,
                    status: "Finished",
                },
                { 
                    movieID: 9,
                    title: 'The Apartment',
                    genre: 'Drama Romance Comedy',
                    director: 'Billy Wilder',
                    movieDate: 1960,
                    rating: 6.3,
                    status: "Finished",
                }
            ],
        };
    }
}